apiVersion: 1
datasources:
  - name: Recipe PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: recipe
    secureJsonData: {password: recipe}
    jsonData: {database: recipes, sslmode: disable, postgresVersion: 1600, timescaledb: false}
